### ISSUE TITLE
virus btw

### ISSUE THREAD

**Issue by ethss** [efenatuyo/roblox-auto-ally#1]
guys dont use this bs

**Comment by efenatuyo** [comment]
how do you come to that conclusion?

**Comment by ethss** [comment]
> to that
the exe file is a virus I decompiled it

**Comment by efenatuyo** [comment]
> > to that
> > the exe file is a virus I decompiled it

you do know that exe is the official tor exe. u can just download it from their site and just compare it. lit the same file 😭 expected more from these skids

**Comment by ethss** [comment]
no i checked the thing

**Comment by efenatuyo** [comment]
> no i checked the thing

so you can you provide evidence or you just gonna say "nuh uh"

**Comment by Crxaw** [comment]
> guys dont use this bs

![image](https://github.com/user-attachments/assets/cdab15cb-f02c-43cd-815c-513d4f03c8fd)

**Comment by BearrXW** [comment]
> > guys dont use this bs
> 
> ![image](https://private-user-images.githubusercontent.com/48805031/350765871-cdab15cb-f02c-43cd-815c-513d4f03c8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Njk2ODksIm5iZiI6MTcyMTU2OTM4OSwicGF0aCI6Ii80ODgwNTAzMS8zNTA3NjU4NzEtY2RhYjE1Y2ItZjAyYy00M2NkLTgxNWMtNTEzZDRmMDNjOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEzNDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGI2NDY5MTg3MzAzNDczOGI3MGFjMGFkMWFlODM3NzlhNmVlY2FhNGI4MzhjY2IwMmU4YWRjNzhjYzdkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-zB4xCp3rDbGl6rtXDB9TPaU2qQuB9effNU9PXPALg)

Wtf u just quoted what everything does 💀💀

**Comment by Crxaw** [comment]
> > > guys dont use this bs
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/48805031/350765871-cdab15cb-f02c-43cd-815c-513d4f03c8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Njk2ODksIm5iZiI6MTcyMTU2OTM4OSwicGF0aCI6Ii80ODgwNTAzMS8zNTA3NjU4NzEtY2RhYjE1Y2ItZjAyYy00M2NkLTgxNWMtNTEzZDRmMDNjOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEzNDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGI2NDY5MTg3MzAzNDczOGI3MGFjMGFkMWFlODM3NzlhNmVlY2FhNGI4MzhjY2IwMmU4YWRjNzhjYzdkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-zB4xCp3rDbGl6rtXDB9TPaU2qQuB9effNU9PXPALg)
> 
> Wtf u just quoted what everything does 💀💀

yeah if it was a rat why would it be open src??

**Comment by BearrXW** [comment]
> > > > guys dont use this bs
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/48805031/350765871-cdab15cb-f02c-43cd-815c-513d4f03c8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Njk2ODksIm5iZiI6MTcyMTU2OTM4OSwicGF0aCI6Ii80ODgwNTAzMS8zNTA3NjU4NzEtY2RhYjE1Y2ItZjAyYy00M2NkLTgxNWMtNTEzZDRmMDNjOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEzNDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGI2NDY5MTg3MzAzNDczOGI3MGFjMGFkMWFlODM3NzlhNmVlY2FhNGI4MzhjY2IwMmU4YWRjNzhjYzdkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-zB4xCp3rDbGl6rtXDB9TPaU2qQuB9effNU9PXPALg)
> > 
> > 
> > Wtf u just quoted what everything does 💀💀
> 
> yeah if it was a rat why would it be open src??

because it needs the source to run u dummy

**Comment by BearrXW** [comment]
> > > > > > guys dont use this bs
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/48805031/350765871-cdab15cb-f02c-43cd-815c-513d4f03c8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Njk2ODksIm5iZiI6MTcyMTU2OTM4OSwicGF0aCI6Ii80ODgwNTAzMS8zNTA3NjU4NzEtY2RhYjE1Y2ItZjAyYy00M2NkLTgxNWMtNTEzZDRmMDNjOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEzNDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGI2NDY5MTg3MzAzNDczOGI3MGFjMGFkMWFlODM3NzlhNmVlY2FhNGI4MzhjY2IwMmU4YWRjNzhjYzdkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-zB4xCp3rDbGl6rtXDB9TPaU2qQuB9effNU9PXPALg)
> > > > 
> > > > 
> > > > Wtf u just quoted what everything does 💀💀
> > > 
> > > 
> > > yeah if it was a rat why would it be open src??
> > 
> > 
> > because it needs the source to run u dummy
> 
> okay but why would you leave a virus open src??? are you that dumb?

Oh shit I just looked over it and I thought that you were the one saying it was a virus my bad bro

**Comment by efenatuyo** [comment]
sanest conversation

**Comment by Stormyplex** [comment]
💀

**Comment by w1ll777** [comment]
oh yeah I'm sure a random exe from a github profile with a cookie logger on it is legit guys!
![Image](https://github.com/user-attachments/assets/112ec1d7-c8ff-4b3f-ac03-7d74657272e4)
![Image](https://github.com/user-attachments/assets/9dd69074-d1fb-43df-a370-6657ad26b2b7)

**Comment by efenatuyo** [comment]
> oh yeah I'm sure a random exe from a github profile with a cookie logger on it is legit guys! ![Image](https://github.com/user-attachments/assets/112ec1d7-c8ff-4b3f-ac03-7d74657272e4) ![Image](https://github.com/user-attachments/assets/9dd69074-d1fb-43df-a370-6657ad26b2b7)

download tor over their official site and compare their hashes before you accuse someone for something stupid with your little brain
