### ISSUE TITLE
only certain amount of groups get allied

### ISSUE THREAD

**Issue by Stormyplex** [efenatuyo/roblox-auto-ally#2]
only the groups which also use an ally bot get sent ally requests
![image](https://github.com/user-attachments/assets/1c84bd92-b967-4f58-9f91-806439fb5613)
please make it random groups

**Comment by efenatuyo** [comment]
The method of scraping is finding recently created clothes then scraping the groups of these clothes and going through their allies and adding these to the list too. This will just get the most active groups if it is random groups you won’t see that much success

**Comment by Stormyplex** [comment]
would it be possible to add an option for a starting point?
for example, if you start on groupID 1 it will send an ally request to groups 1 then send ally requests to the allies of group 1 and then the allies of the allies of group 1 ect

**Comment by efenatuyo** [comment]
could be done but i dont really find that usefull. i can probally send you a snippet here where it has it but it is a little more manual

**Comment by Stormyplex** [comment]
please do 🙏🙏
