### ISSUE TITLE
please add a group starting point

### ISSUE THREAD

**Issue by AWZ3153** [efenatuyo/roblox-auto-ally#5]
it only allys recently made clothing groups 😵

**Comment by efenatuyo** [comment]
> it only allys recently made clothing groups 😵

nope look deeper into it.

**Comment by AWZ3153** [comment]
it only allys recently made clothing groups and their allies which leads to an infinite train, this would be fixed by adding a group id starting point or something like that

**Comment by efenatuyo** [comment]
so allying groups that are active and already have allies is considered as something worse than a group id starting point?
i would say a group id starting point is way worse than this method since you will be having allot of inactive groups

**Comment by AWZ3153** [comment]
for example if you were in a certain community which you know is active and want to ally them and their allies really fast you could use a group starting point which is way more useful than just a couple random clothing groups

**Comment by efenatuyo** [comment]
i wont consider adding this the whole purpose being getting allies as fast as possible. if you want to get allies that are from a specific community you either have to modify this yourself or look for someone that already has done it

**Comment by AWZ3153** [comment]
ive checked every other group ally bot here and none of them work / are outdated, also im pretty clueless on how python works

**Comment by AWZ3153** [comment]
i have like 700 robux if you want payment 😭

**Comment by efenatuyo** [comment]
https://github.com/efenatuyo/roblox-auto-ally/blob/8f252f5cbdd083c0a89906b9ade6001cc5eaac8e/src/ally_sender.py#L88C13-L88C162
change this line to for group in [group_id, group_id2]:

**Comment by AWZ3153** [comment]
thank you so much bru 🙏
